use alloy::primitives::{Address, U256};
use std::marker::PhantomData;

use crate::{
    error::Result,
    storage::{FieldLocation, Handler, LayoutCtx, Storable, StorableType, StorageCtx, StorageOps},
};

/// Type-safe wrapper for a single EVM storage slot.
///
/// # Type Parameters
///
/// - `T`: The Rust type stored in this slot (must implement `Storable`)
///
/// # Example
///
/// ```ignore
/// // Generated by #[contract] macro:
/// pub mod slots {
///     pub const NAME: U256 = uint!(2_U256);
/// }
/// let name_slot = Slot::<String>::new(slots::NAME, address);
/// ```
///
/// The actual storage operations are handled by generated accessor methods
/// that read/write values using the `PrecompileStorageProvider` trait.
#[derive(Debug, Clone)]
pub struct Slot<T> {
    slot: U256,
    ctx: LayoutCtx,
    address: Address,
    _ty: PhantomData<T>,
}

impl<T> Slot<T> {
    /// Creates a new `Slot` with the given slot number and address.
    ///
    /// This is typically called with slot constants generated by the `#[contract]` macro.
    /// Creates a full-slot accessor. For packed fields, use `new_at_loc` instead.
    #[inline]
    pub fn new(slot: U256, address: Address) -> Self {
        Self {
            slot,
            ctx: LayoutCtx::FULL,
            address,
            _ty: PhantomData,
        }
    }

    /// Creates a new `Slot` with the given slot number, layout context, and address.
    ///
    /// This is used by the handler system to create slots with specific packing contexts.
    #[inline]
    pub fn new_with_ctx(slot: U256, ctx: LayoutCtx, address: Address) -> Self {
        Self {
            slot,
            ctx,
            address,
            _ty: PhantomData,
        }
    }

    /// Creates a new `Slot` with the given base slot number with the given offset and address.
    ///
    /// This is a convenience method for accessing struct fields.
    /// Creates a full-slot accessor. For packed fields, use `new_at_loc` instead.
    #[inline]
    pub fn new_at_offset(base_slot: U256, offset_slots: usize, address: Address) -> Self {
        Self {
            slot: base_slot.saturating_add(U256::from_limbs([offset_slots as u64, 0, 0, 0])),
            ctx: LayoutCtx::FULL,
            address,
            _ty: PhantomData,
        }
    }

    /// Creates a new `Slot` from a `FieldLocation` generated by the `#[derive(Storable)]` macro.
    ///
    /// This is the recommended way to access packed struct fields, combining slot offset
    /// and byte offset information in a type-safe manner.
    ///
    /// This method should only be used with packable types (size < 32 bytes).
    #[inline]
    pub fn new_at_loc(base_slot: U256, loc: FieldLocation, address: Address) -> Self
    where
        T: StorableType,
    {
        debug_assert!(
            T::IS_PACKABLE,
            "`fn new_at_loc` can only be used with packable types"
        );
        Self {
            slot: base_slot.saturating_add(U256::from_limbs([loc.offset_slots as u64, 0, 0, 0])),
            ctx: LayoutCtx::packed(loc.offset_bytes),
            address,
            _ty: PhantomData,
        }
    }

    /// Returns the storage slot number where the underlying type is stored.
    ///
    /// Multi-slot types use consecutive slots from this base slot.
    #[inline]
    pub const fn slot(&self) -> U256 {
        self.slot
    }

    /// Returns the address whose storage this slot accesses.
    #[inline]
    pub const fn address(&self) -> Address {
        self.address
    }

    /// Returns the layout context used to load and store the underlying type.
    #[inline]
    pub const fn ctx(&self) -> LayoutCtx {
        self.ctx
    }

    /// Returns the byte offset within the slot (for packed fields).
    ///
    /// Returns `Some(offset)` if this is a packed slot, `None` if it's a full slot.
    #[inline]
    pub const fn offset(&self) -> Option<usize> {
        self.ctx.packed_offset()
    }
}

impl<T> StorageOps for Slot<T> {
    fn load(&self, slot: U256) -> Result<U256> {
        let storage = StorageCtx;
        storage.sload(self.address, slot)
    }

    fn store(&mut self, slot: U256, value: U256) -> Result<()> {
        let mut storage = StorageCtx;
        storage.sstore(self.address, slot, value)
    }

    fn sinc(&mut self, slot: U256, delta: U256) -> Result<()> {
        let mut storage = StorageCtx;
        storage.sinc(self.address, slot, delta)
    }

    fn sdec(&mut self, slot: U256, delta: U256) -> Result<()> {
        let mut storage = StorageCtx;
        storage.sdec(self.address, slot, delta)
    }
}

impl Slot<U256> {
    /// Increments this slot by `delta`.
    #[inline]
    pub fn sinc(&mut self, delta: U256) -> Result<()> {
        <Self as StorageOps>::sinc(self, self.slot, delta)
    }

    /// Decrements this slot by `delta`.
    #[inline]
    pub fn sdec(&mut self, delta: U256) -> Result<()> {
        <Self as StorageOps>::sdec(self, self.slot, delta)
    }
}

/// Wrapper that routes storage operations through transient storage (TLOAD/TSTORE).
///
/// Created via `Slot::transient()` and used by `t_read()`, `t_write()`, `t_delete()`.
struct TransientOps {
    address: Address,
}

impl StorageOps for TransientOps {
    fn load(&self, slot: U256) -> Result<U256> {
        let storage = StorageCtx;
        storage.tload(self.address, slot)
    }

    fn store(&mut self, slot: U256, value: U256) -> Result<()> {
        let mut storage = StorageCtx;
        storage.tstore(self.address, slot, value)
    }
}

impl<T: Storable> Slot<T> {
    /// Returns a transient storage operations wrapper for this slot's address.
    fn transient(&self) -> TransientOps {
        TransientOps {
            address: self.address,
        }
    }
}

impl<T: Storable> Handler<T> for Slot<T> {
    /// Reads a value from storage at this slot.
    ///
    /// This method delegates to the `Storable::load` implementation,
    /// which may read one or more consecutive slots depending on the type.
    ///
    /// Uses thread-local storage context initialized by [`StorageCtx`].
    ///
    /// # Example
    ///
    /// ```ignore
    /// let name_slot = Slot::<String>::new(slots::NAME, address_rc);
    /// let name = name_slot.read().unwrap();
    /// ```
    #[inline]
    fn read(&self) -> Result<T> {
        T::load(self, self.slot, self.ctx)
    }

    /// Writes a value to storage at this slot.
    ///
    /// This method delegates to the `Storable::store` implementation,
    /// which may write one or more consecutive slots depending on the type.
    ///
    /// Uses thread-local storage context initialized by [`StorageCtx`].
    ///
    /// # Example
    ///
    /// ```ignore
    /// let mut name_slot = Slot::<String>::new(slots::NAME, address_rc);
    /// name_slot.write("MyToken".to_string()).unwrap();
    /// ```
    #[inline]
    fn write(&mut self, value: T) -> Result<()> {
        value.store(self, self.slot, self.ctx)
    }

    /// Deletes the value at this slot (sets all slots to zero).
    ///
    /// This method delegates to the `Storable::delete` implementation,
    /// which sets the appropriate slots to zero.
    ///
    /// Uses thread-local storage context initialized by [`StorageCtx`].
    ///
    /// # Example
    ///
    /// ```ignore
    /// let mut name_slot = Slot::<String>::new(slots::NAME, address_rc);
    /// name_slot.delete().unwrap();
    /// ```
    #[inline]
    fn delete(&mut self) -> Result<()> {
        T::delete(self, self.slot, self.ctx)
    }

    /// Reads a value from transient storage at this slot.
    #[inline]
    fn t_read(&self) -> Result<T> {
        T::load(&self.transient(), self.slot, self.ctx)
    }

    /// Writes a value to transient storage at this slot.
    #[inline]
    fn t_write(&mut self, value: T) -> Result<()> {
        value.store(&mut self.transient(), self.slot, self.ctx)
    }

    /// Deletes the value at this slot in transient storage (sets to zero).
    #[inline]
    fn t_delete(&mut self) -> Result<()> {
        T::delete(&mut self.transient(), self.slot, self.ctx)
    }
}


