[package]
name = "tempo-precompiles"
description = "Tempo EVM precompile implementations (vendored from tempoxyz/tempo)"

version = "1.11.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[lints]
workspace = true

[dependencies]
tempo-contracts.workspace = true
tempo-chainspec = { workspace = true, features = ["evm"] }
tempo-primitives = { workspace = true, features = ["evm"] }
tempo-precompiles-macros.workspace = true
alloy = { workspace = true, features = ["sol-types", "consensus"] }
alloy-evm = { workspace = true, features = ["std"] }
alloy-primitives = { workspace = true, features = ["map-foldhash"] }
keccak-const.workspace = true
revm.workspace = true
paste.workspace = true
bitflags.workspace = true

commonware-cryptography.workspace = true
commonware-codec.workspace = true

tracing.workspace = true
thiserror.workspace = true
derive_more.workspace = true
scoped-tls = "1.0"
serde = { workspace = true, optional = true }
serde_json = { workspace = true, optional = true }

[dev-dependencies]
base64.workspace = true
alloy-signer.workspace = true
alloy-signer-local.workspace = true
alloy-primitives = { workspace = true, features = ["rand"] }
eyre.workspace = true
minicbor = { version = "=2.3.0", features = ["alloc"] }
p256 = { workspace = true, features = ["ecdsa"] }
p384 = "0.13"
rand_08 = { package = "rand", version = "0.8.5" }

[features]
default = ["std"]
std = []
